site_url: https://www.nwg-gral.de
logo_url: /assets/images/logo.svg
load_config_file: true
local_backend: true
backend:
  name: github
  repo: nwg-gral/website
  branch: main
  base_url: https://www.nwg-gral.de
  auth_endpoint: /api/oauth/authorize
  auth_scope: repo
  squash_merges: true
  commit_messages:
    create: "content(create): {{collection}} '{{slug}}'"
    update: "content(update): {{collection}} '{{slug}}'"
    delete: "content(delete): {{collection}} '{{slug}}'"
    uploadMedia: "content(upload): '{{path}}'"
    deleteMedia: "content(delete): '{{path}}'"
# publish_mode: editorial_workflow
media_folder: public/assets/cms
public_folder: /assets/cms
editor:
  preview: false
i18n:
  structure: multiple_folders
  locales: ["de", "en"]
  default_locale: "de"
collections:
  # - name: metadata
  #   label: Metadata
  #   format: json
  #   files:
  #     - name: site
  #       label: Website metadata
  #       file: content/metadata/site.json
  #       fields:
  #         - name: address
  #           label: Address

  - name: pages
    label: Pages
    i18n:
      structure: single_file
    format: yaml-frontmatter
    extension: mdx
    files:
      - name: home
        label: Landing page
        file: content/pages/index.mdx
        i18n: true
        fields:
          - name: title
            label: Title
            i18n: true
          - name: body
            label: Description
            widget: markdown
            required: false
            i18n: true

      - name: team
        label: Team page
        file: content/pages/team.mdx
        i18n: true
        fields:
          - name: title
            label: Title
            i18n: true
          - name: body
            label: Description
            widget: markdown
            required: false
            i18n: true

      - name: research
        label: Research page
        file: content/pages/research.mdx
        i18n: true
        fields:
          - name: title
            label: Title
            i18n: true
          - name: body
            label: Description
            widget: markdown
            required: false
            i18n: true
          - name: cards
            label: Cards
            label_singular: Card
            widget: list
            required: false
            i18n: true
            fields:
              - name: title
                label: Title
                i18n: true
              - name: text
                label: Text
                widget: markdown
                required: false
                i18n: true

      - name: networks
        label: Networks page
        file: content/pages/networks.mdx
        i18n: true
        fields:
          - name: title
            label: Title
            i18n: true
          - name: body
            label: Description
            widget: markdown
            required: false
            i18n: true
          - name: cooperationPartners
            label: Cooperation partners
            widget: object
            i18n: true
            fields:
              - name: title
                label: Title
                i18n: true
              - name: text
                label: Text
                widget: markdown
                required: false
                i18n: true
          - name: internationalAdvisoryBoard
            label: International advisory board
            widget: object
            i18n: true
            fields:
              - name: title
                label: Title
                i18n: true
              - name: text
                label: Text
                widget: markdown
                required: false
                i18n: true
          - name: networks
            label: Networks
            widget: object
            i18n: true
            fields:
              - name: title
                label: Title
                i18n: true
              - name: text
                label: Text
                widget: markdown
                required: false
                i18n: true

      - name: activities
        label: Activities page
        file: content/pages/activities.mdx
        i18n: true
        fields:
          - name: title
            label: Title
            i18n: true
          - name: body
            label: Description
            widget: markdown
            required: false
            i18n: true
          - name: events
            label: Events
            widget: object
            i18n: true
            fields:
              - name: title
                label: Title
                i18n: true
              - name: text
                label: Text
                widget: markdown
                required: false
                i18n: true
          - name: publications
            label: Publications
            widget: object
            i18n: true
            fields:
              - name: title
                label: Title
                i18n: true
              - name: text
                label: Text
                widget: markdown
                required: false
                i18n: true

      - name: contact
        label: Contact
        file: content/pages/contact.mdx
        i18n: true
        fields:
          - name: title
            label: Title
            i18n: true
          - name: body
            label: Description
            widget: markdown
            required: false
            i18n: true

      - name: imprint
        label: Imprint
        file: content/pages/imprint.mdx
        i18n: true
        fields:
          - name: title
            label: Title
            i18n: true
          - name: body
            label: Description
            widget: markdown
            required: false
            i18n: true

  - name: team
    label: Team
    label_singular: Team member
    folder: content/team
    i18n: true
    format: yaml-frontmatter
    extension: mdx
    create: true
    delete: true
    sortable_fields:
      - commit_date
      - lastName
    slug: "{{lastName}}-{{firstName}}"
    summary: "{{firstName}} {{lastName}}"
    identifier_field: lastName
    fields:
      - name: title
        label: Title
        required: false
        i18n: duplicate
      - name: firstName
        label: First name
        i18n: duplicate
      - name: lastName
        label: Last name
        i18n: duplicate
      - name: role
        label: Role
        i18n: true
      - name: email
        label: Email
        i18n: duplicate
        required: false
      - name: website
        label: Website
        required: false
        i18n: duplicate
      - name: cv
        label: CV
        required: false
        i18n: true
      - name: image
        label: Image
        widget: image
        i18n: duplicate
      - name: bosslevel
        label: Boss level
        widget: number
        i18n: duplicate
      - name: body
        label: Description
        widget: markdown
        i18n: true

  - name: cooperation-partners
    label: Cooperation partners
    label_singular: Cooperation partner
    folder: content/networks/cooperation-partners
    i18n: true
    format: yaml-frontmatter
    extension: mdx
    create: true
    delete: true
    sortable_fields:
      - commit_date
      - name
    slug: "{{name}}"
    summary: "{{name}}"
    identifier_field: name
    fields:
      - name: name
        label: Name
        i18n: duplicate
      - name: website
        label: Website
        i18n: duplicate
      - name: body
        label: Description
        widget: markdown
        i18n: true

  - name: international-advisory-board
    label: International advisory board
    label_singular: International advisory board member
    folder: content/networks/international-advisory-board
    i18n: true
    format: yaml-frontmatter
    extension: mdx
    create: true
    delete: true
    sortable_fields:
      - commit_date
      - name
    slug: "{{name}}"
    summary: "{{name}}"
    identifier_field: name
    fields:
      - name: name
        label: Name
        i18n: duplicate
      - name: website
        label: Website
        i18n: duplicate
      - name: body
        label: Description
        widget: markdown
        i18n: true

  - name: networks
    label: Partners
    label_singular: Partner
    folder: content/networks/networks
    i18n: true
    format: yaml-frontmatter
    extension: mdx
    create: true
    delete: true
    sortable_fields:
      - commit_date
      - name
    slug: "{{name}}"
    summary: "{{name}}"
    identifier_field: name
    fields:
      - name: name
        label: Name
        i18n: duplicate
      - name: website
        label: Website
        i18n: duplicate
      - name: body
        label: Description
        widget: markdown
        i18n: true

  - name: events
    label: Events or lectures
    label_singular: Event or lecture
    folder: content/events
    i18n: true
    format: yaml-frontmatter
    extension: mdx
    create: true
    delete: true
    sortable_fields:
      - commit_date
      - title
      - date
    slug: "{{title}}"
    summary: "{{title}}"
    identifier_field: title
    fields:
      - name: title
        label: Title
        i18n: true
      - name: date
        label: Date
        widget: datetime
        format: "YYYY-MM-DD"
        date_format: "YYYY-MM-DD"
        time_format: false
        required: true
        i18n: duplicate
      - name: url
        label: URL
        required: false
        i18n: duplicate
      - name: featured
        label: Featured event
        required: false
        widget: boolean
        i18n: duplicate
      - name: body
        label: Description
        widget: markdown
        i18n: true

  - name: publications
    label: Publications
    label_singular: Publication
    folder: content/publications
    i18n: true
    format: yaml-frontmatter
    extension: mdx
    create: true
    delete: true
    sortable_fields:
      - commit_date
      - title
      - date
    slug: "{{title}}"
    summary: "{{title}}"
    identifier_field: title
    fields:
      - name: title
        label: Title
        i18n: duplicate
      - name: date
        label: Date
        widget: datetime
        format: "YYYY-MM-DD"
        date_format: "YYYY-MM-DD"
        time_format: false
        required: true
        i18n: duplicate
      - name: url
        label: URL
        required: false
        i18n: duplicate
      - name: attachments
        label: Attachments
        label_singular: Attachment
        widget: list
        required: false
        i18n: true
        fields:
          - name: label
            label: Label
            i18n: true
          - name: file
            label: File
            widget: file
            i18n: true
      - name: featured
        label: Featured publication
        required: false
        widget: boolean
        i18n: duplicate
      - name: body
        label: Description
        widget: markdown
        i18n: true
